#!/usr/bin/env bash
python main_crmodel.py --config_name=pre_shuffle_no_repeatemo_no_weight_shuffle_co_train_restore --gpu=0 --vali_test_ses=2 --vali_type=F --test_type=M --restore_file=/home/ddy/projects/emotions/ser_nn_spectrogram/cr_output2/pre_shuffle_no_repeatemo_no_weight_shuffle/bestacc_ckpt/08181515_e2vFtM
python main_crmodel.py --config_name=pre_shuffle_no_repeatemo_no_weight_shuffle_co_train_restore --gpu=0 --vali_test_ses=3 --vali_type=M --test_type=F --restore_file=/home/ddy/projects/emotions/ser_nn_spectrogram/cr_output2/pre_shuffle_no_repeatemo_no_weight_shuffle/bestacc_ckpt/08181515_e3vMtF
python main_crmodel.py --config_name=pre_shuffle_no_repeatemo_no_weight_shuffle_co_train_restore --gpu=0 --vali_test_ses=0 --vali_type=F --test_type=M --restore_file=/home/ddy/projects/emotions/ser_nn_spectrogram/cr_output2/pre_shuffle_no_repeatemo_no_weight_shuffle/bestacc_ckpt/08181516_e0vFtM
python main_crmodel.py --config_name=pre_shuffle_no_repeatemo_no_weight_shuffle_co_train_restore --gpu=0 --vali_test_ses=2 --vali_type=M --test_type=F --restore_file=/home/ddy/projects/emotions/ser_nn_spectrogram/cr_output2/pre_shuffle_no_repeatemo_no_weight_shuffle/bestacc_ckpt/08181851_e2vMtF
python main_crmodel.py --config_name=pre_shuffle_no_repeatemo_no_weight_shuffle_co_train_restore --gpu=0 --vali_test_ses=0 --vali_type=M --test_type=F --restore_file=/home/ddy/projects/emotions/ser_nn_spectrogram/cr_output2/pre_shuffle_no_repeatemo_no_weight_shuffle/bestacc_ckpt/08181937_e0vMtF
python main_crmodel.py --config_name=pre_shuffle_no_repeatemo_no_weight_shuffle_co_train_restore --gpu=0 --vali_test_ses=3 --vali_type=F --test_type=M --restore_file=/home/ddy/projects/emotions/ser_nn_spectrogram/cr_output2/pre_shuffle_no_repeatemo_no_weight_shuffle/bestacc_ckpt/08182226_e3vFtM
python main_crmodel.py --config_name=pre_shuffle_no_repeatemo_no_weight_shuffle_co_train_restore --gpu=0 --vali_test_ses=4 --vali_type=F --test_type=M --restore_file=/home/ddy/projects/emotions/ser_nn_spectrogram/cr_output2/pre_shuffle_no_repeatemo_no_weight_shuffle/bestacc_ckpt/08182357_e4vFtM
python main_crmodel.py --config_name=pre_shuffle_no_repeatemo_no_weight_shuffle_co_train_restore --gpu=0 --vali_test_ses=4 --vali_type=M --test_type=F --restore_file=/home/ddy/projects/emotions/ser_nn_spectrogram/cr_output2/pre_shuffle_no_repeatemo_no_weight_shuffle/bestacc_ckpt/08190040_e4vMtF
python main_crmodel.py --config_name=pre_shuffle_no_repeatemo_no_weight_shuffle_co_train_restore --gpu=0 --vali_test_ses=1 --vali_type=F --test_type=M --restore_file=/home/ddy/projects/emotions/ser_nn_spectrogram/cr_output2/pre_shuffle_no_repeatemo_no_weight_shuffle/bestacc_ckpt/08191105_e1vFtM
python main_crmodel.py --config_name=pre_shuffle_no_repeatemo_no_weight_shuffle_co_train_restore --gpu=0 --vali_test_ses=1 --vali_type=M --test_type=F --restore_file=/home/ddy/projects/emotions/ser_nn_spectrogram/cr_output2/pre_shuffle_no_repeatemo_no_weight_shuffle/bestacc_ckpt/08191451_e1vMtF
