#!/usr/bin/env bash
python main_crmodel.py --config_name=not_seq_len_weight_shuffle_co_train_restore --gpu=1 --vali_test_ses=0 --vali_type=F --test_type=M --restore_file=/home/ddy/projects/emotions/ser_nn_spectrogram/cr_output2/not_seq_len_weight_shuffle/bestacc_ckpt/08142210_e0vFtM
python main_crmodel.py --config_name=not_seq_len_weight_shuffle_co_train_restore --gpu=1 --vali_test_ses=1 --vali_type=F --test_type=M --restore_file=/home/ddy/projects/emotions/ser_nn_spectrogram/cr_output2/not_seq_len_weight_shuffle/bestacc_ckpt/08142210_e1vFtM
python main_crmodel.py --config_name=not_seq_len_weight_shuffle_co_train_restore --gpu=1 --vali_test_ses=2 --vali_type=F --test_type=M --restore_file=/home/ddy/projects/emotions/ser_nn_spectrogram/cr_output2/not_seq_len_weight_shuffle/bestacc_ckpt/08142210_e2vFtM
python main_crmodel.py --config_name=not_seq_len_weight_shuffle_co_train_restore --gpu=1 --vali_test_ses=1 --vali_type=M --test_type=F --restore_file=/home/ddy/projects/emotions/ser_nn_spectrogram/cr_output2/not_seq_len_weight_shuffle/bestacc_ckpt/08150017_e1vMtF
python main_crmodel.py --config_name=not_seq_len_weight_shuffle_co_train_restore --gpu=1 --vali_test_ses=2 --vali_type=M --test_type=F --restore_file=/home/ddy/projects/emotions/ser_nn_spectrogram/cr_output2/not_seq_len_weight_shuffle/bestacc_ckpt/08150018_e2vMtF
python main_crmodel.py --config_name=not_seq_len_weight_shuffle_co_train_restore --gpu=1 --vali_test_ses=0 --vali_type=M --test_type=F --restore_file=/home/ddy/projects/emotions/ser_nn_spectrogram/cr_output2/not_seq_len_weight_shuffle/bestacc_ckpt/08150020_e0vMtF
python main_crmodel.py --config_name=not_seq_len_weight_shuffle_co_train_restore --gpu=1 --vali_test_ses=3 --vali_type=F --test_type=M --restore_file=/home/ddy/projects/emotions/ser_nn_spectrogram/cr_output2/not_seq_len_weight_shuffle/bestacc_ckpt/08150220_e3vFtM
python main_crmodel.py --config_name=not_seq_len_weight_shuffle_co_train_restore --gpu=1 --vali_test_ses=4 --vali_type=M --test_type=F --restore_file=/home/ddy/projects/emotions/ser_nn_spectrogram/cr_output2/not_seq_len_weight_shuffle/bestacc_ckpt/08150229_e4vMtF
python main_crmodel.py --config_name=not_seq_len_weight_shuffle_co_train_restore --gpu=1 --vali_test_ses=4 --vali_type=F --test_type=M --restore_file=/home/ddy/projects/emotions/ser_nn_spectrogram/cr_output2/not_seq_len_weight_shuffle/bestacc_ckpt/08150233_e4vFtM
python main_crmodel.py --config_name=not_seq_len_weight_shuffle_co_train_restore --gpu=1 --vali_test_ses=3 --vali_type=M --test_type=F --restore_file=/home/ddy/projects/emotions/ser_nn_spectrogram/cr_output2/not_seq_len_weight_shuffle/bestacc_ckpt/08150436_e3vMtF
