default: &DEFAULT
  batch_size: 32
#  train_epochs: [2]
#  lrs: [0.0003]
  train_epochs: [20, 20, 20]
  lrs: [0.0003, 0.0002, 0.0001]
  #  mode: train # mode: train, re-train, eval
  data_dir: '/home/ddy/projects/emotions/data/Spectrogram_EN_Var'
#  data_dir: '/home/ddy/projects/emotions/data/Spectrogram_EN_Var_simple'
  emos: ['neu', 'ang', 'hap', 'sad']
  sess: ['Ses01', 'Ses02', 'Ses03', 'Ses04', 'Ses05']
  consider_sent_types: ['impro']
  vali_type: 'M'
  test_type: 'F'
  vali_test_ses: 1

  cnn_kernels: [[3, 3, 1, 8], [3, 3, 8, 8], [3, 3, 8, 16], [3, 3, 16, 16]]
  rnn_hidden_size: 128
  fc_hiddens: [64]
  fc_keep_prob: 0.5

  CUDA_VISIBLE_DEVICES: '1'
  gpu_allow_growth: False

  is_weighted_loss: True
  is_post_calc_len: False
  is_seq_len_weight: True
  is_shuffle_train: True
  is_norm_weight: False
  is_save_emo_result: False
#  is_process_result_train: False
#  is_save_hrnn_feature: False

  is_train: True
  is_restore: False

  feature_size: 400
  optimizer_type: 'adam'
  loss_reduction: MEAN # MEAN, SUM_BY_NONZERO_WEIGHTS

  id_prefix: ''
  # update when pre-process
  id: ''
  id_str: ''
  out_dir: ./cr_output/cr_output_no_weighted_loss
  tf_log_fold: tf_log
  log_fold: log
  result_fold: result
  cfg_out_fold: cfg
  ckpt_fold: ckpt
  bestloss_ckpt_fold: bestloss_ckpt
  bestacc_ckpt_fold: bestacc_ckpt


  gt_npy: 'gt_'
  pr_npy: 'pr_'
  sid_npy: 'sid_'
  ts_npy: 'ts_'

  is_log_beside: True
  stdout_level: 2
  log_level: 0

  best_params_type: bestacc # bestloss, bestacc
  restore_file: '/home/ddy/projects/emotions/ser_nn_spectrogram/cr_output/bestacc_ckpt/07172216_e1vMtF'
  restart_train_epoch: 5
  persist_interval: 20
  saver_max_to_keep: 30

  is_pre_shuffle: False
  repeat_emos: [1, 2]
  is_repeat_emos: True

debug:
  <<: *DEFAULT
  best_params_type: bestloss
  train_epochs: [2]
  lrs: [0.0003]
  out_dir: ./output_debug
  stdout_level: 0
  CUDA_VISIBLE_DEVICES: '2'
  data_dir: '/home/ddy/projects/emotions/data/Spectrogram_EN_Var_simple'

not_seq_len_weight:
  <<: *DEFAULT
  is_seq_len_weight: False
  is_shuffle_train: False
  out_dir: ./cr_output2/not_seq_len_weight

script_not_seq_len_weight:
  <<: *DEFAULT
  is_seq_len_weight: False
  consider_sent_types: ['script']
  is_shuffle_train: False
  out_dir: ./cr_output2/script_not_seq_len_weight


not_weight:
  <<: *DEFAULT
  is_weighted_loss: False
  is_shuffle_train: False
  out_dir: ./cr_output2/not_weight_not_shuffle

not_seq_len_weight_shuffle: &NOT_SEQ_LEN_WEIGHT_SHUFFLE
  <<: *DEFAULT
  is_seq_len_weight: False
  is_shuffle_train: True
  out_dir: ./cr_output2/not_seq_len_weight_shuffle2

mix_data: &MIX_DATA
  <<: *DEFAULT
  consider_sent_types: ['impro', 'script']
  out_dir: ./cr_output2/mix_data_shuffle
  is_shuffle_train: True

mix_data_no_shuffle:
  <<: *MIX_DATA
  out_dir: ./cr_output2/mix_data_no_shuffle
  is_shuffle_train: False

pre_shuffle_no_weight_shuffle:
  <<: *DEFAULT
  is_weighted_loss: False
  is_shuffle_train: True
  is_pre_shuffle: True
  out_dir: ./cr_output2/pre_shuffle_no_weight_shuffle

pre_shuffle_no_repeatemo_no_weight_shuffle: &PRE_SHUFFLE_NO_REPEATEMO_NO_WEIGHT_SHUFFLE
  <<: *DEFAULT
  is_weighted_loss: False
  is_shuffle_train: True
  is_pre_shuffle: True
  is_repeat_emos: False
  out_dir: ./cr_output2/pre_shuffle_no_repeatemo_no_weight_shuffle

restore:
  <<: *NOT_SEQ_LEN_WEIGHT_SHUFFLE
  out_dir: ./cr_output2/restore/
  is_train: True
  is_restore: True
  restore_file: '/home/ddy/projects/emotions/ser_nn_spectrogram/cr_output2/not_seq_len_weight_shuffle2/ckpt/08151645_e4vFtM-2214'
  is_save_emo_result: True
  vali_type: 'M'
  test_type: 'F'
  vali_test_ses: 4
  id_prefix: 'eval_train'
  stdout_level: 1
  train_epochs: [100]
  lrs: [0.0003]


