lr_steps: [2]
lrs: [0.003]
batch_size: 32
anchor_batch_size: 80
anchors_per_emo: 20
emos: [neu, ang, hap, sad]
consider_sent_types: [impro, script]
sess: [Ses01, Ses02, Ses03, Ses04, Ses05]
vali_type: M
test_type: F
vali_test_ses: 4
eval_fold: ./eval_txts/
select_anchors_strategy: random
is_pre_shuffle: false
repeat_emos: [1, 2]
is_repeat_emos: true
cnn_kernels: [[3, 3, 1, 8], [3, 3, 8, 8], [3, 3, 8, 16], [3, 3, 16, 16]]
rnn_hidden_size: 128
fc_hiddens: [64]
feature_size: 400
optimizer_type: adam
is_log_beside: true
stdout_level: 0
log_level: 0
CUDA_VISIBLE_DEVICES: '0'
gpu_allow_growth: false
id_prefix: ''
id: '08211603'
id_str: 08211603_e4vMtF
out_dir: ./relativenet_out/default
tf_log_fold: tf_log
log_fold: log
result_fold: result
cfg_out_fold: cfg
ckpt_fold: ckpt
bestloss_ckpt_fold: bestloss_ckpt
bestacc_ckpt_fold: bestacc_ckpt
gt_npy: gt_08211603_e4vMtF.npy
pr_npy: pr_08211603_e4vMtF.npy
best_params_type: ''
restore_file: /home/ddy/projects/emotions/ser_nn_spectrogram/cr_output/bestacc_ckpt/07172216_e1vMtF
restart_train_steps: 5
persist_interval: 1000
train_eval_interval: 10
eval_interval: 10
is_eval_test: false
saver_max_to_keep: 30
is_save_emo_result: false
is_train: true
is_restore: false
config_file: ./RelativeNet/RNModel.yml
config_name: default
gpu: '0'
tf_log_dir: ./relativenet_out/default/tf_log
result_dir: ./relativenet_out/default/result
cfg_out_dir: ./relativenet_out/default/cfg
ckpt_dir: ./relativenet_out/default/ckpt
bestloss_ckpt_dir: ./relativenet_out/default/bestloss_ckpt
bestacc_ckpt_dir: ./relativenet_out/default/bestacc_ckpt
log_dir: ./relativenet_out/default/log
ckpt_path: ./relativenet_out/default/ckpt/08211603_e4vMtF
bestloss_ckpt_path: ./relativenet_out/default/bestloss_ckpt/08211603_e4vMtF
bestacc_ckpt_path: ./relativenet_out/default/bestacc_ckpt/08211603_e4vMtF
gt_npy_path: ./relativenet_out/default/result/gt_08211603_e4vMtF.npy
pr_npy_path: ./relativenet_out/default/result/pr_08211603_e4vMtF.npy
sid_npy_path: ./relativenet_out/default/result/sid_08211603_e4vMtF.npy
ts_npy_path: ./relativenet_out/default/result/ts_08211603_e4vMtF.npy
result_txt_path: ./relativenet_out/default/log/result_08211603_e4vMtF.txt
result_matrix_path: ./relativenet_out/default/result/matrix_08211603_e4vMtF.npy
log_path: ./relativenet_out/default/log/08211603_e4vMtF.log
