lr_steps: [50000]
lrs: [0.0003]
batch_size: 32
anchor_batch_size: 40
anchors_per_emo: 6
train2_k: 50
emos: [neu, ang, hap, sad]
data_dir: /home/ddy/projects/emotions/data/Spectrogram_EN_Var
consider_sent_types: [impro]
sess: [Ses01, Ses02, Ses03, Ses04, Ses05]
vali_type: F
test_type: M
vali_test_ses: 4
eval_fold: ./RelativeNet/eval_txts/
select_anchors_strategy: random
is_pre_shuffle: false
repeat_emos: [1, 2]
is_repeat_emos: true
cnn_kernels: [[3, 3, 1, 8], [3, 3, 8, 8], [3, 3, 8, 16], [3, 3, 16, 16]]
rnn_hidden_size: 128
fc_hiddens: [64]
fc_kprob: 0.5
feature_size: 400
optimizer_type: adam
is_log_beside: true
stdout_level: 0
log_level: 0
CUDA_VISIBLE_DEVICES: '2'
gpu_allow_growth: false
id_prefix: ''
id: '08221012'
id_str: 08221012_e4vFtM
out_dir: ./relativenet_out/default
tf_log_fold: tf_log
log_fold: log
result_fold: result
cfg_out_fold: cfg
ckpt_fold: ckpt
bestloss_ckpt_fold: bestloss_ckpt
bestacc_ckpt_fold: bestacc_ckpt
gt_npy: gt_08221012_e4vFtM.npy
pr_npy: pr_08221012_e4vFtM.npy
best_params_type: ''
restore_file: /home/ddy/projects/emotions/ser_nn_spectrogram/cr_output/bestacc_ckpt/07172216_e1vMtF
restart_train_steps: 5
persist_interval: 3000
train_eval_interval: 30
eval_interval: 10
eval_interval2: 500
is_eval_test: true
saver_max_to_keep: 30
is_save_emo_result: false
is_train: true
is_restore: false
config_file: ./RelativeNet/RNModel.yml
config_name: default
gpu: '2'
tf_log_dir: ./relativenet_out/default/tf_log
result_dir: ./relativenet_out/default/result
cfg_out_dir: ./relativenet_out/default/cfg
ckpt_dir: ./relativenet_out/default/ckpt
bestloss_ckpt_dir: ./relativenet_out/default/bestloss_ckpt
bestacc_ckpt_dir: ./relativenet_out/default/bestacc_ckpt
log_dir: ./relativenet_out/default/log
ckpt_path: ./relativenet_out/default/ckpt/08221012_e4vFtM
bestloss_ckpt_path: ./relativenet_out/default/bestloss_ckpt/08221012_e4vFtM
bestacc_ckpt_path: ./relativenet_out/default/bestacc_ckpt/08221012_e4vFtM
gt_npy_path: ./relativenet_out/default/result/gt_08221012_e4vFtM.npy
pr_npy_path: ./relativenet_out/default/result/pr_08221012_e4vFtM.npy
sid_npy_path: ./relativenet_out/default/result/sid_08221012_e4vFtM.npy
ts_npy_path: ./relativenet_out/default/result/ts_08221012_e4vFtM.npy
result_txt_path: ./relativenet_out/default/log/result_08221012_e4vFtM.txt
result_matrix_path: ./relativenet_out/default/result/matrix_08221012_e4vFtM.npy
log_path: ./relativenet_out/default/log/08221012_e4vFtM.log
