#!/usr/bin/env bash

echo 'test alpha'

python main_cr_mel.py --config_file=./cr_model_v2/cfgs/mel_rediv_impro_batch64_nodropout.yml --config_name=ce_center_m11_origin_lambda03_alpha01 --gpu=2 --vali_type='8' --test_type='9'
python main_cr_mel.py --config_file=./cr_model_v2/cfgs/mel_rediv_impro_batch64_nodropout.yml --config_name=ce_center_m11_origin_lambda03_alpha02 --gpu=2 --vali_type='8' --test_type='9'
python main_cr_mel.py --config_file=./cr_model_v2/cfgs/mel_rediv_impro_batch64_nodropout.yml --config_name=ce_center_m11_origin_lambda03_alpha03 --gpu=2 --vali_type='8' --test_type='9'
python main_cr_mel.py --config_file=./cr_model_v2/cfgs/mel_rediv_impro_batch64_nodropout.yml --config_name=ce_center_m11_origin_lambda03_alpha04 --gpu=2 --vali_type='8' --test_type='9'
python main_cr_mel.py --config_file=./cr_model_v2/cfgs/mel_rediv_impro_batch64_nodropout.yml --config_name=ce_center_m11_origin_lambda03_alpha05 --gpu=2 --vali_type='8' --test_type='9'
python main_cr_mel.py --config_file=./cr_model_v2/cfgs/mel_rediv_impro_batch64_nodropout.yml --config_name=ce_center_m11_origin_lambda03_alpha06 --gpu=2 --vali_type='8' --test_type='9'
python main_cr_mel.py --config_file=./cr_model_v2/cfgs/mel_rediv_impro_batch64_nodropout.yml --config_name=ce_center_m11_origin_lambda03_alpha07 --gpu=2 --vali_type='8' --test_type='9'
python main_cr_mel.py --config_file=./cr_model_v2/cfgs/mel_rediv_impro_batch64_nodropout.yml --config_name=ce_center_m11_origin_lambda03_alpha08 --gpu=2 --vali_type='8' --test_type='9'
python main_cr_mel.py --config_file=./cr_model_v2/cfgs/mel_rediv_impro_batch64_nodropout.yml --config_name=ce_center_m11_origin_lambda03_alpha09 --gpu=2 --vali_type='8' --test_type='9'
python main_cr_mel.py --config_file=./cr_model_v2/cfgs/mel_rediv_impro_batch64_nodropout.yml --config_name=ce_center_m11_origin_lambda03_alpha10 --gpu=2 --vali_type='8' --test_type='9'

python main_cr_mel.py --config_file=./cr_model_v2/cfgs/mel_rediv_impro_batch64_nodropout.yml --config_name=ce_center_m11_origin_lambda03_alpha01 --gpu=2 --vali_type='8' --test_type='9'
python main_cr_mel.py --config_file=./cr_model_v2/cfgs/mel_rediv_impro_batch64_nodropout.yml --config_name=ce_center_m11_origin_lambda03_alpha02 --gpu=2 --vali_type='8' --test_type='9'
python main_cr_mel.py --config_file=./cr_model_v2/cfgs/mel_rediv_impro_batch64_nodropout.yml --config_name=ce_center_m11_origin_lambda03_alpha03 --gpu=2 --vali_type='8' --test_type='9'
python main_cr_mel.py --config_file=./cr_model_v2/cfgs/mel_rediv_impro_batch64_nodropout.yml --config_name=ce_center_m11_origin_lambda03_alpha04 --gpu=2 --vali_type='8' --test_type='9'
python main_cr_mel.py --config_file=./cr_model_v2/cfgs/mel_rediv_impro_batch64_nodropout.yml --config_name=ce_center_m11_origin_lambda03_alpha05 --gpu=2 --vali_type='8' --test_type='9'
python main_cr_mel.py --config_file=./cr_model_v2/cfgs/mel_rediv_impro_batch64_nodropout.yml --config_name=ce_center_m11_origin_lambda03_alpha06 --gpu=2 --vali_type='8' --test_type='9'
python main_cr_mel.py --config_file=./cr_model_v2/cfgs/mel_rediv_impro_batch64_nodropout.yml --config_name=ce_center_m11_origin_lambda03_alpha07 --gpu=2 --vali_type='8' --test_type='9'
python main_cr_mel.py --config_file=./cr_model_v2/cfgs/mel_rediv_impro_batch64_nodropout.yml --config_name=ce_center_m11_origin_lambda03_alpha08 --gpu=2 --vali_type='8' --test_type='9'
python main_cr_mel.py --config_file=./cr_model_v2/cfgs/mel_rediv_impro_batch64_nodropout.yml --config_name=ce_center_m11_origin_lambda03_alpha09 --gpu=2 --vali_type='8' --test_type='9'
python main_cr_mel.py --config_file=./cr_model_v2/cfgs/mel_rediv_impro_batch64_nodropout.yml --config_name=ce_center_m11_origin_lambda03_alpha10 --gpu=2 --vali_type='8' --test_type='9'

python main_cr_mel.py --config_file=./cr_model_v2/cfgs/mel_rediv_impro_batch64_nodropout.yml --config_name=ce_center_m11_origin_lambda03_alpha01 --gpu=2 --vali_type='8' --test_type='9'
python main_cr_mel.py --config_file=./cr_model_v2/cfgs/mel_rediv_impro_batch64_nodropout.yml --config_name=ce_center_m11_origin_lambda03_alpha02 --gpu=2 --vali_type='8' --test_type='9'
python main_cr_mel.py --config_file=./cr_model_v2/cfgs/mel_rediv_impro_batch64_nodropout.yml --config_name=ce_center_m11_origin_lambda03_alpha03 --gpu=2 --vali_type='8' --test_type='9'
python main_cr_mel.py --config_file=./cr_model_v2/cfgs/mel_rediv_impro_batch64_nodropout.yml --config_name=ce_center_m11_origin_lambda03_alpha04 --gpu=2 --vali_type='8' --test_type='9'
python main_cr_mel.py --config_file=./cr_model_v2/cfgs/mel_rediv_impro_batch64_nodropout.yml --config_name=ce_center_m11_origin_lambda03_alpha05 --gpu=2 --vali_type='8' --test_type='9'
python main_cr_mel.py --config_file=./cr_model_v2/cfgs/mel_rediv_impro_batch64_nodropout.yml --config_name=ce_center_m11_origin_lambda03_alpha06 --gpu=2 --vali_type='8' --test_type='9'
python main_cr_mel.py --config_file=./cr_model_v2/cfgs/mel_rediv_impro_batch64_nodropout.yml --config_name=ce_center_m11_origin_lambda03_alpha07 --gpu=2 --vali_type='8' --test_type='9'
python main_cr_mel.py --config_file=./cr_model_v2/cfgs/mel_rediv_impro_batch64_nodropout.yml --config_name=ce_center_m11_origin_lambda03_alpha08 --gpu=2 --vali_type='8' --test_type='9'
python main_cr_mel.py --config_file=./cr_model_v2/cfgs/mel_rediv_impro_batch64_nodropout.yml --config_name=ce_center_m11_origin_lambda03_alpha09 --gpu=2 --vali_type='8' --test_type='9'
python main_cr_mel.py --config_file=./cr_model_v2/cfgs/mel_rediv_impro_batch64_nodropout.yml --config_name=ce_center_m11_origin_lambda03_alpha10 --gpu=2 --vali_type='8' --test_type='9'
